<script lang="ts">
  import AiMark from '../ui/AiMark.svelte';
  import { modelName, type ModelPick } from '../../lib/chat/providers/index';

  let { model, text = false }: { model?: ModelPick; text?: boolean } = $props();
</script>

<span class="ai-tag"><AiMark byline={model ? `Generated by ${modelName(model)}` : undefined} />{#if text}<span class="words">AI-generated</span>{/if}</span>

<style>
  .ai-tag{display:inline-flex;align-items:baseline;gap:4px;vertical-align:baseline}
  .words{font-family:var(--sans);font-size:0.72rem;color:var(--muted)}
</style>
