<script lang="ts">
  /* Every exercise the shelf and the reader's model hold, by the concept it
     tests. A generated one names the model that wrote it and can be deleted;
     the attempts made on it stay. */
  import { practice } from '../../lib/practice/store.svelte';
  import { books } from '../../lib/practice/books.svelte';
  import { generated } from '../../lib/practice/generated.svelte';
  import { modelName } from '../../lib/chat/providers/index';
  import { mathHtml } from '../actions/math';
  import AiMark from '../ui/AiMark.svelte';

  let { shelf }: { shelf: readonly string[] } = $props();

  let q = $state('');
  let opened = $state(false);
  let row = $state<string | null>(null);
  const LIMIT = 60;
  const plain = (s: string): string => s.replace(/\$([^$]*)\$/g, '$1').replace(/<[^>]*>/g, '');
  const bookItems = $derived.by(() => {
    const out = new Map<string, { section: string; id: string; prompt: string }[]>();
    practice.catalog().exercises.filter((e) => e.ex.place.at === 'end').forEach((e) => e.ex.concepts.forEach((c) => {
      const list = out.get(c) ?? []; list.push({ section: e.section, id: e.ex.id, prompt: e.ex.prompt }); out.set(c, list);
    }));
    return out;
  });
  const rows = $derived.by(() => {
    const ids = [...new Set([...bookItems.keys(), ...generated.list.flatMap((g) => g.concepts)])];
    const needle = q.trim().toLowerCase();
    return ids.map((id) => ({ id, name: practice.conceptOf(id)?.name ?? id }))
      .filter((r) => !needle || plain(r.name).toLowerCase().includes(needle) || r.id.includes(needle))
      .sort((a, b) => plain(a.name).localeCompare(plain(b.name)));
  });
  const toggle = (e: Event): void => {
    opened = (e.currentTarget as HTMLDetailsElement).open;
    if (opened) shelf.forEach((b) => { if ((books.status[b] ?? 'idle') === 'idle') books.load(b).catch(() => {}); });
  };
</script>

<details class="panel" ontoggle={toggle}>
  <summary class="head">Exercises by concept</summary>
  {#if opened}
    <input class="find" type="search" placeholder="Filter concepts…" aria-label="Filter concepts" bind:value={q}>
    <ul class="list">
      {#each rows.slice(0, LIMIT) as r (r.id)}
        {@const own = bookItems.get(r.id) ?? []}
        {@const made = generated.forConcept(r.id)}
        <li>
          <button type="button" class="concept" aria-expanded={row === r.id} onclick={() => (row = row === r.id ? null : r.id)}>
            <span class="twisty" class:open={row === r.id}>▸</span>
            <span class="lab"><span use:mathHtml={r.name}></span></span>
            <span class="count">book {own.length}{#if made.length} · generated {made.length}{/if}</span>
          </button>
          {#if row === r.id}
            <ul class="items">
              {#each own as e (`${e.section}/${e.id}`)}
                <li class="item"><span class="src">{e.section} · {e.id}</span><div class="prompt" use:mathHtml={e.prompt}></div></li>
              {/each}
              {#each made as g (g.id)}
                <li class="item">
                  <span class="src">{g.facet}<AiMark byline={`Generated by ${modelName(g.model)}`} /></span>
                  <div class="prompt" use:mathHtml={g.prompt}></div>
                  <button type="button" class="btn" onclick={() => generated.remove(g.id)}>Delete</button>
                </li>
              {/each}
            </ul>
          {/if}
        </li>
      {/each}
    </ul>
    {#if rows.length > LIMIT}<p class="quiet">The first {LIMIT} are listed; type to narrow them.</p>{/if}
  {/if}
</details>

<style>
  .panel{background:var(--panel);border:1px solid var(--rule);border-radius:12px;padding:12px 14px}
  .head{font-family:var(--sans);font-size:1.08rem;font-weight:700;letter-spacing:-0.01em;cursor:pointer}
  .quiet{color:var(--muted);margin:2px 0}
  .find{width:100%;box-sizing:border-box;font:inherit;font-size:0.8rem;padding:6px 10px;margin:8px 0;border:1px solid var(--rule);border-radius:8px;background:var(--panel);color:var(--ink)}
  .list,.items{list-style:none;margin:0;padding:0}
  .concept{display:flex;align-items:center;gap:6px;width:100%;font:inherit;text-align:left;background:none;border:0;border-radius:6px;padding:3px 4px;color:var(--ink);cursor:pointer}
  .concept:hover{background:var(--soft)}
  .twisty{color:var(--muted);transition:transform .12s}
  .twisty.open{transform:rotate(90deg)}
  .lab{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .count{flex:none;color:var(--muted);font-size:.74rem;font-variant-numeric:tabular-nums}
  .items{padding:4px 0 8px 22px;display:flex;flex-direction:column;gap:8px}
  .item{display:flex;flex-direction:column;gap:2px;border-left:2px solid var(--rule);padding-left:8px}
  .src{color:var(--muted);font-size:.72rem}
  .prompt{font-size:.85rem}
  .btn{align-self:flex-end;font:inherit;font-size:0.74rem;font-weight:600;padding:2px 9px;border:1px solid var(--rule);background:var(--panel);color:var(--ink);border-radius:7px;cursor:pointer}
  .btn:hover{background:var(--soft)}
  button:focus-visible{outline:2px solid var(--accent);outline-offset:1px}
</style>
