import { test } from 'node:test';
import assert from 'node:assert/strict';
import { sectionSourceUrl, frontPageSourceUrl, attributionOf, footerHtml, citation, nameList, aiSentence, aiByline, aiNames, aiPartsByline } from '../src/lib/content/attribution';
import { markAiFigures } from '../src/lib/content/fragment';
import { AiCreditSchema, FigureSchema, parseAiMakers, type BookDTO, type ChapterDTO } from '../src/lib/content/schema';
import { aiMarkHtml, AI_MARK_HTML } from '../src/components/ui/aimark';

const FABLE = [{ model: 'claude-fable-5-1' as const }], OPUS5 = [{ model: 'claude-opus-5' as const, effort: 'high' as const }];

test('the old prose credit parses into makers, the principal first', () => {
  assert.deepEqual(parseAiMakers('Claude Opus 5, with Claude Fable 5.1 and Claude Opus 5.5'), [{ model: 'claude-opus-5' }, { model: 'claude-fable-5-1' }, { model: 'claude-opus-5-5' }]);
  assert.deepEqual(parseAiMakers('Someone else'), [{ model: 'claude-opus-5' }]);
  assert.deepEqual(AiCreditSchema.parse({ text: 'Claude Opus 5.5', figures: [{ model: 'claude-opus-5-5', effort: 'low' }] }),
    { text: [{ model: 'claude-opus-5-5' }], figures: [{ model: 'claude-opus-5-5', effort: 'low' }] });
  assert.throws(() => AiCreditSchema.parse({ text: [{ model: ' ' }], figures: FABLE }));
});
test('any model may be credited, and one without a known name is shown by its id', () => {
  const credit = AiCreditSchema.parse({ text: [{ model: 'gpt-astra', effort: 'high' }], figures: FABLE });
  assert.equal(aiByline(credit.text), 'Generated by gpt-astra · high effort');
  assert.equal(aiNames([...credit.text, ...FABLE]), 'gpt-astra, with Claude Fable 5.1');
});
test('the mark names its model and effort on hover', () => {
  assert.equal(aiByline([{ model: 'claude-opus-5-5', effort: 'low' }]), 'Generated by Claude Opus 5.5 · low effort');
  assert.equal(aiByline([...OPUS5, ...FABLE]), 'Generated by Claude Opus 5 · high effort, with Claude Fable 5.1');
  assert.equal(aiByline(undefined), undefined);
  assert.equal(aiNames([...OPUS5, ...FABLE]), 'Claude Opus 5, with Claude Fable 5.1');
  assert.match(aiMarkHtml(aiByline(OPUS5)), /title="Generated by Claude Opus 5 · high effort"/);
  assert.match(AI_MARK_HTML, /title="AI generated"/);
});
test('a figure that keeps its own list names what each model did, a line each', () => {
  const parts = [{ model: 'claude-opus-5', effort: 'high' as const, part: 'scene, controls and readout' }, { model: 'claude-fable-5-1', part: 'hand and outline' }];
  assert.equal(aiPartsByline(parts), 'Generated by Claude Opus 5 · high effort: scene, controls and readout\nClaude Fable 5.1: hand and outline');
  assert.match(aiMarkHtml(aiPartsByline(parts)), /title="Generated by Claude Opus 5 · high effort: scene, controls and readout&#10;Claude Fable 5.1: hand and outline"/);
  assert.throws(() => FigureSchema.parse({ id: 'sim-a', kind: 'sim', ai: [{ model: 'claude-opus-5', part: '' }] }));
  assert.throws(() => FigureSchema.parse({ id: 'sim-a', kind: 'sim', ai: [{ model: 'claude-opus-5', part: 'x'.repeat(81) }] }));
  assert.throws(() => FigureSchema.parse({ id: 'sim-a', kind: 'sim', ai: [] }));
  const fig = (id: string): string => `<figure class="sim" id="${id}"><div class="sim-head"><span class="eyebrow">Sim</span></div></figure>`;
  const html = fig('sim-a') + fig('sim-b'), rows = [FigureSchema.parse({ id: 'sim-a', kind: 'sim', ai: parts })];
  const titles = [...markAiFigures(html, 'Generated by Claude Opus 5.5', rows).matchAll(/title="([^"]*)"/g)].map((m) => m[1]);
  assert.deepEqual(titles, [aiMarkHtml(aiPartsByline(parts)).match(/title="([^"]*)"/)![1], 'Generated by Claude Opus 5.5']);
  assert.equal(markAiFigures(html, undefined, []), html);
  assert.equal([...markAiFigures(html, undefined, rows).matchAll(/ai-mark/g)].length, 1);
});

const book: BookDTO = {
  id: 'college-physics-2e', title: 'College Physics 2e', publisher: 'OpenStax', authors: ['Paul Peter Urone', 'Roger Hinrichs'],
  sourceUrl: 'https://openstax.org/details/books/college-physics-2e', copyright: 'Rice University', license: 'CC BY-NC-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  openstax: 'https://openstax.org/books/college-physics-2e/pages/', chapterDirs: ['ch02'], types: [], symbols: [], exerciseKinds: [], concepts: [], conceptPrereqs: [], sheets: [],
};
const AT = 'https://openstax.org/books/college-physics-2e/pages/2-1-displacement';
const chapter: ChapterDTO = { id: '2', dir: 'ch02', title: 'Kinematics', sections: [{ id: '2.1', title: 'Displacement', slug: '2-1-displacement' }, { id: '2.2', title: 'Vectors' }], variables: [] };

test('nameList joins like prose', () => {
  assert.equal(nameList([]), ''); assert.equal(nameList(['A']), 'A'); assert.equal(nameList(['A', 'B']), 'A and B'); assert.equal(nameList(['A', 'B', 'C']), 'A, B and C');
});
test('section source url needs both the prefix and a slug', () => {
  assert.equal(sectionSourceUrl(book, chapter, '2.1'), 'https://openstax.org/books/college-physics-2e/pages/2-1-displacement');
  assert.equal(sectionSourceUrl(book, chapter, '2.2'), undefined);
  assert.equal(sectionSourceUrl({ openstax: undefined }, chapter, '2.1'), undefined);
});
test('an introduction or summary page is credited from the record that names it', () => {
  assert.equal(frontPageSourceUrl(book, { module: 'm42122', slug: '2-introduction-to-one-dimensional-kinematics' }), 'https://openstax.org/books/college-physics-2e/pages/2-introduction-to-one-dimensional-kinematics');
  assert.equal(frontPageSourceUrl(book, { module: 'm42122' }), undefined);
  assert.equal(frontPageSourceUrl(book, undefined), undefined);
});
test('footer carries author, publisher, copyright, licence, access line and notes', () => {
  const a = attributionOf(book, { openstax: AT, notes: 'Problems 2 and 4 are left out.', ai: undefined });
  const html = footerHtml(a);
  assert.match(html, /^<footer class="footer">/);
  assert.match(html, /<cite>College Physics 2e<\/cite> by Paul Peter Urone and Roger Hinrichs/);
  assert.match(html, /\(<a href="https:\/\/openstax.org\/details\/books\/college-physics-2e">OpenStax<\/a>, © Rice University\), /);
  assert.match(html, /<a href="https:\/\/creativecommons.org\/licenses\/by-nc-sa\/4.0\/" rel="license">CC BY-NC-SA 4.0<\/a>/);
  assert.match(html, /shared under the same licence/);
  assert.match(html, /Access for free at <a href="https:\/\/openstax.org\/books\/college-physics-2e\/pages\/2-1-displacement">openstax.org\/books\/college-physics-2e\/pages\/2-1-displacement<\/a>\./);
  assert.match(html, /<p>Problems 2 and 4 are left out.<\/p><\/footer>$/);
});
test('footer names the AI by role, folded when one model did both', () => {
  const both = footerHtml(attributionOf(book, { openstax: AT, notes: 'Problems 2 and 4 are left out.', ai: { text: FABLE, figures: FABLE } }));
  assert.match(both, /<\/p><p>The text was transformed and the simulations were built by Claude Fable 5.1.<\/p><p>Problems 2 and 4 are left out.<\/p><\/footer>$/);
  assert.equal(aiSentence({ text: FABLE, figures: OPUS5 }), 'The text was transformed by Claude Fable 5.1 and the simulations were built by Claude Opus 5.');
  assert.equal(aiSentence(undefined), '');
  assert.doesNotMatch(footerHtml(attributionOf(book, { openstax: AT, notes: '', ai: undefined })), /transformed/);
});
test('footer without optional fields still reads', () => {
  const html = footerHtml(attributionOf({ ...book, authors: [], sourceUrl: undefined, copyright: undefined, licenseUrl: undefined, openstax: undefined }, { notes: '', ai: undefined }));
  assert.match(html, /<cite>College Physics 2e<\/cite> \(OpenStax\), CC BY-NC-SA 4.0,/);
  assert.doesNotMatch(html, /Access for free/);
  assert.doesNotMatch(html, /<p><\/p>/);
});
test('footer escapes the book\u2019s own fields and sets the notes as the swept markup they are', () => {
  const html = footerHtml(attributionOf({ ...book, title: 'A <b>' }, { openstax: AT, notes: 'measured from <span class="katex">x</span>', ai: undefined }));
  assert.match(html, /<cite>A &lt;b&gt;<\/cite>/);
  /* the notes are swept for math when the page is read, so the footer sets them rather than escaping them away */
  assert.match(html, /<p>measured from <span class="katex">x<\/span><\/p>/);
});
test('citation is plain text with the access line', () => {
  assert.equal(citation(attributionOf(book, { openstax: AT, notes: '', ai: undefined })),
    'College Physics 2e by Paul Peter Urone and Roger Hinrichs, OpenStax, © Rice University, CC BY-NC-SA 4.0, adapted by OmniStax and shared under the same licence. Access for free at https://openstax.org/books/college-physics-2e/pages/2-1-displacement.');
  assert.equal(citation(attributionOf(book, { openstax: AT, notes: '', ai: { text: FABLE, figures: FABLE } })),
    'College Physics 2e by Paul Peter Urone and Roger Hinrichs, OpenStax, © Rice University, CC BY-NC-SA 4.0, adapted by OmniStax and shared under the same licence. Access for free at https://openstax.org/books/college-physics-2e/pages/2-1-displacement. The text was transformed and the simulations were built by Claude Fable 5.1.');
});
